### ISSUE TITLE
Check the current template files, decide on adding new ones

### ISSUE THREAD

**Issue by rbiswas4** [rbiswas4/midway_snfiles#6]
@reneehlozek As you said you wanted to check the files, please compare the files in `https://github.com/rbiswas4/midway_snfiles/tree/master/build_snana_inputs/data` with the ones you have used and confirm that they are good (or tell us what should be changed). Also, we may need to have multiple templates, so let us get a list of template files needed.

**Comment by reneehlozek** [comment]
The SIM files are the same as the ones I've been using for the SRD!
